class player{
    constructor(layer,x,y){
        this.layer=layer
        this.position={x:x,y:y}
        this.chunk=0
        this.direction=0
        this.fade=1
        this.time=0
        this.remove=false
    }
    display(){
        this.layer.translate(this.position.x,this.position.y)
        this.layer.rotate(this.direction)
        this.layer.noFill()
        this.layer.stroke(255,this.fade/2)
        this.layer.strokeWeight(3)
        this.layer.ellipse(0,0,180,180)
        this.layer.noStroke()
        this.layer.fill(150,255,150,this.fade)
        this.layer.ellipse(0,0,24,24)
        this.layer.ellipse(0,-90,24,24)
        this.layer.rotate(-this.direction)
        this.layer.translate(-this.position.x,-this.position.y)
    }
    update(){
        this.direction+=gameplay.speed
        if(this.direction>360){
            this.direction-=360
        }
    }
    move(){
        if(this.chunk<entities.chunks.length-1&&abs(this.direction-entities.chunks[this.chunk].direction)<gameplay.range||abs(this.direction-entities.chunks[this.chunk].direction-360)<gameplay.range||abs(this.direction-entities.chunks[this.chunk].direction+360)<gameplay.range){
            this.chunk++
            this.position.x=entities.chunks[this.chunk].position.x
            this.position.y=entities.chunks[this.chunk].position.y
            this.direction+=180
        }
    }
}